from .topic import TopicFactory
from .question import QuestionFactory
from .course import CourseFactory
from .exam import ExamFactory
from .user import UserFactory
from .lesson import LessonFactory
from .result_test import ResultTestFactory
from .certificate import CertificateFactory
from .context import ContextFactory
from .lesson_learned import LessonLearnedFactory
from .register import RegisterFactory
