from .course_view_test import CourseViewTest, ListCourseTestCase
from .detail_course_view_test import DetailCourseViewTest
from .summary_view_test import SummaryLearningTest
from .lesson_learned_view_test import LessonContentTest
