# Generated by Django 4.2.2 on 2023-07-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cover_img",
            field=models.ImageField(blank=True, null=True, upload_to="course_img/"),
        ),
    ]
