# Generated by Django 4.2.2 on 2023-07-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_manager", "0002_course_cover_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basic", "Basic"),
                    ("medium", "Medium"),
                    ("intermediate", "Intermediate"),
                ],
                null=True,
            ),
        ),
    ]
