# Generated by Django 4.2.2 on 2023-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_manager", "0003_course_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basic", "Basic"),
                    ("medium", "Medium"),
                    ("Advanced", "advanced"),
                ],
                null=True,
            ),
        ),
    ]
