# Generated by Django 4.2.2 on 2023-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_manager", "0006_remove_course_register_course_register"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="register",
        ),
        migrations.AddField(
            model_name="course",
            name="register",
            field=models.IntegerField(default=0),
        ),
    ]
