# Generated by Django 4.2.2 on 2023-07-24 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_manager", "0006_alter_course_teacher"),
        ("course_manager", "0008_register"),
    ]

    operations = []
