# Generated by Django 4.2.2 on 2023-07-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_manager", "0013_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
