# Generated by Django 4.2.2 on 2023-07-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_manager", "0014_alter_lesson_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="resulttest",
            name="pass_exam",
            field=models.BooleanField(default=False),
        ),
    ]
