# Generated by Django 4.2.2 on 2023-06-28 04:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="fullname",
            new_name="full_name",
        ),
    ]
