# Generated by Django 4.2.2 on 2023-06-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0002_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fullname",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
