# Generated by Django 4.2.2 on 2023-06-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0003_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cover_img",
            field=models.ImageField(upload_to="cover_img/"),
        ),
    ]
