# Generated by Django 4.2.2 on 2023-06-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0003_user_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_img",
            field=models.ImageField(default="", upload_to=None),
            preserve_default=False,
        ),
    ]
