# Generated by Django 4.2.2 on 2023-06-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0005_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "student"), (1, "teacher")]
            ),
        ),
    ]
