# Generated by Django 4.2.2 on 2023-06-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0007_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher")]
            ),
        ),
    ]
