# Generated by Django 4.2.2 on 2023-06-28 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0008_alter_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Created At",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
    ]
