from .certificate import Certificate
from .course import Course
from .exam import Exam
from .lesson import Lesson
from .lesson_learned import LessonLearned
from .question import Question
from .register import Register
from .result_test import ResultTest
from .topic import Topic
